linters:
  # Enable all available linters.
  # Default: false
  disable-all: true
  enable:
    - asciicheck
    - copyloopvar
    - bodyclose
    - dogsled
    - dupl
    - err113
    - errcheck
    - exhaustive
    - gochecknoglobals
    - gochecknoinits
    - goconst
    - gocritic
    - godot
    - godox
    - goheader
    - gomodguard
    - goprintffuncname
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - mnd
    - nakedret
    - nolintlint
    - prealloc
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - stylecheck
    - testpackage
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
    - wsl

linters-settings:
  wsl:
    strict-append: false
    enforce-err-cuddling: true
  
  mnd:
    # Values always ignored: "1", "1.0", "0" and "0.0"
    # Default: []
    ignored-numbers:
      - '2'

issues:
  exclude-rules:
    - path: api/api.go
      text: "mnd: Magic number: (10|64), in <argument> detected"