version: "2"
linters:
  default: none
  enable:
    - asciicheck
    - bodyclose
    - copyloopvar
    - dogsled
    - dupl
    - err113
    - errcheck
    - gochecknoglobals
    - gochecknoinits
    - goconst
    - gocritic
    - godot
    - godox
    - goheader
    - gomodguard
    - goprintffuncname
    - govet
    - ineffassign
    - misspell
    - mnd
    - nakedret
    - nolintlint
    - prealloc
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - testpackage
    - unconvert
    - unparam
    - unused
    - whitespace
    - wsl_v5
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - path: pkg/output/banner.go
        text: 'should be written without leading space as `//nolint: gochecknoglobals`'
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
