services:
  mongo:
    container_name: mongo
    image: "mongo:latest"
    expose:
      - "27017" # exposed only internally
    restart: always
    volumes:
      - "/boggart-data:/data/db"
  boggart:
    build: "."
    depends_on:
      - 'mongo'
    ports:
      - "8092:8092" # honeypot
      - "8093:8093" # dashboard
      - "8094:8094" # API
    restart: always
